version: "3.9"

services:
  db:
    image: postgres:15
    container_name: courseplanner-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: course_planner
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: courseplanner-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@db:5432/course_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: course_planner
      SECRET_KEY: supersecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: courseplanner-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data: